/**
 * Reserved username list — labels that cannot be claimed as
 * `username.audric.sui` leaf subnames. The main impersonation/squat defense
 * beyond format validation. Every route that mints or checks a handle MUST go
 * through `isReserved()`. Ported from web-v2 (206 entries); categories kept for
 * human auditors. All entries MUST be lowercase.
 */

const RESERVED = [
  // §7.1 — baseline: system / role / access
  "admin",
  "support",
  "audric",
  "team",
  "root",
  "api",
  "www",
  "mod",
  "mods",
  "staff",
  "official",
  "verify",
  "verified",
  "help",
  "info",
  "mail",
  "system",
  "bot",
  "bots",
  "notification",
  // footguns / null states
  "null",
  "undefined",
  "test",
  // Audric product names
  "pay",
  "send",
  "receive",
  "swap",
  "save",
  "borrow",
  "repay",
  "store",
  "passport",
  "intelligence",
  "finance",
  // squat magnets
  "mom",
  "dad",

  // §7.2 — Audric brand variants (phishing primitives)
  "audric-team",
  "audric-support",
  "audric-official",
  "audric-help",
  "audric-pay",
  "audric-store",
  "audric-finance",
  "audric-passport",
  "audric-intelligence",
  "audric-bot",
  "audric-admin",
  "audric-system",

  // §7.3 — web/ops generics (app routes)
  "app",
  "dashboard",
  "account",
  "settings",
  "setting",
  "profile",
  "login",
  "signin",
  "signup",
  "register",
  "auth",
  "callback",
  "status",
  "docs",
  "faq",
  "blog",
  "news",

  // §7.4 — crypto primitives + financial verbs (fund-routing impersonation)
  "wallet",
  "treasury",
  "vault",
  "pool",
  "dao",
  "defi",
  "lend",
  "lending",
  "invest",
  "yield",
  "stake",
  "unstake",
  "claim",
  "deposit",
  "withdraw",
  "transfer",
  "fee",
  "fees",
  "refund",
  "refunds",
  "gas",
  "bridge",
  "escrow",
  "safe",

  // §7.5 Tier A — Sui ecosystem brands
  "sui",
  "mysten",
  "mystenlabs",
  "navi",
  "cetus",
  "volo",
  "walrus",
  "scallop",
  "kriya",
  "suiet",
  "phantom",
  "suins",
  "slush",

  // §7.5 Tier B — major crypto/exchange brands
  "bitcoin",
  "btc",
  "ethereum",
  "eth",
  "circle",
  "usdc",
  "binance",
  "coinbase",
  "kraken",
  "okx",
  "bybit",
  "coingecko",
  "coinmarketcap",

  // §7.6 — regulator / government
  "sec",
  "irs",
  "fed",
  "fbi",
  "ofac",
  "cftc",
  "fincen",

  // §7.7 — abuse magnets / footguns / null-state primitives
  "none",
  "void",
  "nil",
  "nan",
  "error",
  "deleted",
  "removed",
  "banned",
  "anonymous",
  "anon",
  "unknown",
  "placeholder",

  // §7.8a — static-route sentinels (Next.js special files / top-level routes)
  "new",
  "chat",
  "invoice",
  "litepaper",
  "privacy",
  "terms",
  "disclaimer",
  "security",
  "icon",
  "favicon",
  "manifest",
  "robots",
  "sitemap",
  "opengraph-image",

  // §7.8b — future-product reservation
  "credit",
  "savings",
  "portfolio",
  "portfolios",
  "balance",
  "balances",
  "home",
  "feed",
  "inbox",
  "notifications",
  "search",
  "explore",
  "discover",
  "onboarding",
  "welcome",
  "report",
  "reports",
  "analytics",
  "wallets",
  "goals",
  "goal",
  "memories",
  "preferences",
  "watch",
  "activity",
  "activities",
  "contacts",
  "recipes",

  // §7.8c — operator / brand pages
  "about",
  "contact",
  "company",
  "press",
  "media",
  "careers",
  "jobs",
  "hiring",
  "investors",
  "investor",
  "shareholders",
  "board",
  "advisors",
  "partners",
  "partner",
  "ambassador",
  "ambassadors",
  "pricing",
  "plans",
  "plan",
  "billing",
  "subscription",
  "premium",
  "upgrade",

  // §7.8d — legal / compliance
  "legal",
  "tos",
  "eula",
  "policy",
  "gdpr",
  "cookies",
  "compliance",
] as const;

/** Reserved set — canonical lowercase. Lookup is case-insensitive via isReserved(). */
export const RESERVED_USERNAMES: ReadonlySet<string> = new Set(RESERVED);

/**
 * True if the label is reserved. Does NOT re-validate format — the caller must
 * run `validateAudricLabel` first.
 */
export function isReserved(label: string): boolean {
  return RESERVED_USERNAMES.has(label.trim().toLowerCase());
}
