-- [P4.1 follow-up — 2026-05-25] Drop dead `TurnMetrics.todoUpdateCount`
-- column. Engine v3.0.0 (commit e2b87530) deleted the `update_todo`
-- tool entirely. Pre-3.0.0 the column tracked one increment per
-- `todo_update` engine event; post-3.0.0 the event no longer fires
-- and the host's `telemetry-integration.ts` was hardcoding `0` on
-- every row write — a dead column by construction.
--
-- The original purpose was the SPEC 8 v0.5.1 B3.6 LEAN-turn regression
-- check: "any non-zero `todoUpdateCount` on a `harnessShape='lean'`
-- row is a shape-contract violation." That regression class disappears
-- with the tool — the harness-shape "no todos on lean turns" contract
-- is now structurally enforced (no tool means no count means no
-- shape-violation row to flag).
--
-- Companion changes shipped in this commit:
--   - REMOVED column from `prisma/schema.prisma` TurnMetrics model
--     + reworded the harnessShape regression comment
--   - REMOVED hardcoded `todoUpdateCount: 0` write from
--     `lib/audric/telemetry-integration.ts:333`
--
-- The `lib/generated/prisma/*` client regenerates from schema.prisma
-- via `prisma generate` (the postinstall hook) — picks up the column
-- removal automatically. No manual edits to generated files.
--
-- `thinkingBlockCount` survives because the engine v3.0.0 still emits
-- `thinking_done` events and the column is still being populated by
-- the same dashboard segmentation.
--
-- IRREVERSIBLE. Take a Neon PITR snapshot if you need a rollback path.

-- AlterTable
ALTER TABLE "TurnMetrics" DROP COLUMN IF EXISTS "todoUpdateCount";
