import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Audric — Terms of Service',
  description: 'Terms of Service for the Audric AI financial assistant.',
};

export default function TermsPage() {
  return (
    <>
      <header className="mb-12">
        <Link
          href="/"
          className="inline-block text-fg-secondary hover:text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-8 transition-colors"
        >
          &larr; audric.ai
        </Link>
        <h1 className="font-serif text-[36px] sm:text-[44px] leading-[1.1] tracking-[-0.01em] text-fg-primary mb-3">
          Terms of Service
        </h1>
        <p className="font-mono text-[10px] tracking-[0.1em] uppercase text-fg-muted">Last updated · April 2026 (v2)</p>
      </header>

      <div className="space-y-10 text-fg-secondary leading-[1.7] text-[14px]">
        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            1. Acceptance
          </h2>
          <p>
            By using Audric (&quot;the Service&quot;), including the web app at
            audric.ai, you agree to these Terms of Service. If you do not
            agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            2. Description of Service
          </h2>
          <p>
            Audric is an AI-powered financial assistant built on the Sui
            blockchain. It helps you manage savings, earn yield through DeFi
            protocols, swap tokens, send and receive funds, borrow against
            collateral, and interact with on-chain services through natural
            conversation. Audric is built on{' '}
            <a
              href="https://t2000.ai"
              target="_blank"
              rel="noopener noreferrer"
              className="text-fg-primary underline underline-offset-2 hover:opacity-70"
            >
              t2000
            </a>{' '}
            infrastructure. The Service is provided as-is and is currently in{' '}
            <strong className="text-fg-primary">beta</strong>.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            3. Authentication and Wallet
          </h2>
          <p>
            Audric uses zkLogin via Google sign-in, powered by Mysten Labs
            Enoki. Your wallet is derived from your Google session &mdash; no
            seed phrases, passwords, or local key files are involved. Your
            wallet address is deterministic based on your Google account. Audric
            never has access to your private keys.
          </p>
          <p className="mt-2">
            If you lose access to your Google account, you may lose access to
            your wallet. Audric cannot recover funds on your behalf.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            4. No Financial Advice
          </h2>
          <p>
            Nothing provided by the Service constitutes financial, investment,
            tax, or legal advice. The AI assistant provides information and
            executes actions on your behalf, but its analysis (including yield
            comparisons, risk assessments, and swap estimates) is generated by a
            language model and may contain errors. DeFi interactions carry
            inherent risks including smart contract risk, impermanent loss, and
            liquidation. You are solely responsible for evaluating these risks
            and making your own decisions.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            5. Third-Party Protocols and Services
          </h2>
          <p>Audric integrates with third-party services including:</p>
          <ul className="list-disc pl-5 space-y-1.5 mt-2">
            <li>
              <strong className="text-fg-primary">DeFi protocols</strong> (NAVI,
              Cetus, VOLO) &mdash; via on-chain smart contracts
            </li>
            <li>
              <strong className="text-fg-primary">AI</strong> (Anthropic) &mdash;
              for the conversational assistant
            </li>
            <li>
              <strong className="text-fg-primary">Authentication</strong> (Google,
              Mysten Labs Enoki) &mdash; for zkLogin and gas sponsorship
            </li>
          </ul>
          <p className="mt-2">
            We do not control, audit, or guarantee the availability, quality, or
            security of third-party services. Use of third-party services is at
            your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            6. Transaction Approval
          </h2>
          <p>
            Audric uses a tiered approval model. Read-only operations (balance
            checks, rate lookups) execute automatically. Write operations that
            move funds (swaps, sends, borrows) require your explicit approval
            before execution. Certain safe write operations (deposits into
            lending vaults, debt repayment, staking) are auto-approved for
            convenience. You are ultimately responsible for reviewing and
            approving each action.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            7. Fees and Charges
          </h2>
          <p>Audric charges the following fees:</p>
          <ul className="list-disc pl-5 space-y-1.5 mt-2">
            <li>
              <strong className="text-fg-primary">Swap overlay fee</strong>{' '}
              &mdash; 0.1% on every token swap, collected as part of the
              transaction
            </li>
            <li>
              <strong className="text-fg-primary">Yield spread</strong> &mdash;
              Audric displays net APY after a small spread on savings yield.
              The exact spread varies by market conditions
            </li>
          </ul>
          <p className="mt-2">
            All other features &mdash; chat, balance lookups, savings deposits
            and withdrawals, sends, borrows, payment links, and rate / health
            factor lookups &mdash; are free to use within the daily session
            limits described in Section 8. Fees may change with notice.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            8. Daily Free Sessions
          </h2>
          <p>
            Audric is free to use within a daily session cap. We count distinct
            chat sessions per wallet over a rolling 24-hour window. Verified
            accounts get a higher cap than unverified ones; the current limits
            are visible in the app. There is no on-chain spending cap or
            features budget &mdash; the previous &ldquo;allowance&rdquo;
            mechanism was retired in April 2026.
          </p>
          <p className="mt-2">
            If you reach the daily limit, new chat sessions are blocked until
            the rolling window resets. Existing transactions, balance lookups,
            and account access continue to work. Verifying your email raises
            the daily cap and is the only billing-relevant action you can take.
          </p>
          <p className="mt-2">
            We may adjust the cap, the window, or the verified / unverified
            tiers at any time based on cost and abuse signals, with notice in
            the app.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            9. Gas Sponsorship
          </h2>
          <p>
            Audric sponsors gas fees for all transactions via Mysten Labs
            Enoki. This is a convenience feature and may be modified,
            rate-limited, or discontinued at any time without notice.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            10. AI Assistant
          </h2>
          <p>
            The AI assistant is powered by large language models. It can make
            mistakes, misinterpret requests, or provide inaccurate financial
            analysis. Always verify important information before acting on it.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            11. Tax Responsibility
          </h2>
          <p>
            Cryptocurrency transactions (including stablecoin swaps) may be
            taxable events in your jurisdiction. You are solely responsible for
            understanding and complying with applicable tax laws. Audric does
            not provide tax advice and does not report to tax authorities on
            your behalf.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            12. Beta Software
          </h2>
          <p>
            Audric is currently in beta. The software may contain bugs, errors,
            or vulnerabilities. We do not guarantee the software will function
            without interruption or error. Use with significant funds is at your
            own risk.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            13. Limitation of Liability
          </h2>
          <p className="uppercase text-xs leading-relaxed">
            To the maximum extent permitted by law, Audric and its contributors
            shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, or any loss of profits, data,
            or funds, whether in contract, tort, or otherwise, arising out of
            or in connection with your use of the Service. This includes but is
            not limited to losses from AI recommendations, DeFi protocol
            interactions, swap execution, and third-party service failures.
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            14. Open Source
          </h2>
          <p>
            Audric is open-source software. The source code is available at{' '}
            <a
              href="https://github.com/mission69b/audric"
              target="_blank"
              rel="noopener noreferrer"
              className="text-fg-primary underline underline-offset-2 hover:opacity-70"
            >
              github.com/mission69b/audric
            </a>
            . Infrastructure code is available at{' '}
            <a
              href="https://github.com/mission69b/t2000"
              target="_blank"
              rel="noopener noreferrer"
              className="text-fg-primary underline underline-offset-2 hover:opacity-70"
            >
              github.com/mission69b/t2000
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-fg-primary font-mono text-[10px] tracking-[0.12em] uppercase mb-4">
            15. Changes
          </h2>
          <p>
            We may update these Terms at any time. Continued use of the Service
            after changes constitutes acceptance of the updated Terms.
          </p>
        </section>
      </div>
    </>
  );
}
